#!/bin/bash
set -e

echo "Generating env.ts..."

GEMINI_API_KEY_VALUE="${API_KEY:='YOUR_GEMINI_API_KEY_NOT_SET'}"
YOUTUBE_API_KEY_VALUE="${YOUTUBE_API_KEY:='YOUR_YOUTUBE_API_KEY_NOT_SET'}"

if [ -z "$GEMINI_API_KEY_VALUE" ]; then
  echo "Warning: GEMINI_API_KEY_VALUE is empty"
fi

if [ -z "$YOUTUBE_API_KEY_VALUE" ]; then
  echo "Warning: YOUTUBE_API_KEY_VALUE is empty"
fi

cat > src/env.ts <<EOL
// This file is auto-generated by build.sh during Vercel build
export const API_KEY = "${GEMINI_API_KEY_VALUE}";
export const YOUTUBE_API_KEY = "${YOUTUBE_API_KEY_VALUE}";
EOL

echo "✅ env.ts generated:"
cat src/env.ts
