#!/bin/bash
set -e

# Create src folder if it doesn't exist
mkdir -p src

echo "Generating env.ts..."

GEMINI_API_KEY_VALUE="${API_KEY:='YOUR_GEMINI_API_KEY_NOT_SET'}"
YOUTUBE_API_KEY_VALUE="${YOUTUBE_API_KEY:='YOUR_YOUTUBE_API_KEY_NOT_SET'}"

cat > src/env.ts <<EOL
// Auto-generated by build.sh
export const API_KEY = "${GEMINI_API_KEY_VALUE}";
export const YOUTUBE_API_KEY = "${YOUTUBE_API_KEY_VALUE}";
EOL

echo "env.ts generated..."
cat src/env.ts
